version: '3.6'

services: 
  elasticsearch:
    container_name: core_elasticsearch
    build:
      context: .//elasticsearch
      args:
        ELK_VERSION: 7.4.0
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: core_elasticsearch
        target: /usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    networks: 
      - default
  logstash:
    container_name: core_logstash
    build:
      context: ./logstash
      args:
        ELK_VERSION: 7.4.0
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: false
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: false
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    ports:
      - "5000:5000"
      - "9600:9600"
    networks: 
      - default
  kibana:
    container_name: core_kibana
    build:
      context: ./kibana/
      args:
        ELK_VERSION: 7.4.0
    ports:
      - "5601:5601"
    restart: unless-stopped
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
      - logstash
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true 
    networks: 
      - default
volumes:
  core_elasticsearch:
networks: 
  default:
    driver: bridge